### ISSUE TITLE
0.8.7 update crashes with "AttributeError: module 'weakref' has no attribute 'WeakValueDict'"

### ISSUE THREAD

**Issue by lnfecteDru** [Gobot1234/steam.py#104]
### Summary

After updating to version 0.8.7 program crashes with "AttributeError: module 'weakref' has no attribute 'WeakValueDict'"

### Reproduction Steps

Update steamio to version 0.8.7
Launch program
Get exception "AttributeError: module 'weakref' has no attribute 'WeakValueDict'"

Code:
```
import json
import steam

bot = steam.Client(state=steam.PersonaState.Online)

@bot.event
async def on_ready():
    print('Client is ready!')

@bot.event
async def on_trade_receive(trade: steam.TradeOffer):
    print('New trade offer received')

@bot.event
async def on_trade_accept(trade: steam.TradeOffer):
    print('Trade offer accepted')

@bot.event
async def on_trade_decline(trade: steam.TradeOffer):
    print('Trade offer declined')

with open('credentials.json') as f:
    credentials = json.load(f)

bot.run(**credentials)
```
_File "credentials.json" contains valid username, password, secret and shared keys_

### Expected Results

Normal program behavior

### Actual Results

Error. Full stacktrace:
```
Traceback (most recent call last):
  File "error.py", line 4, in <module>
    bot = steam.Client(state=steam.PersonaState.Online)
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc_updated\lib\site-packages\steam\client.py", line 145, in __init__
    self._connection = self._get_state(**options)
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc_updated\lib\site-packages\steam\client.py", line 159, in _get_state
    return ConnectionState(client=self, **options)
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc_updated\lib\site-packages\steam\state.py", line 144, in __init__
    self.clear()
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc_updated\lib\site-packages\steam\state.py", line 147, in clear
    self._users: weakref.WeakValueDict[int, User] = weakref.WeakValueDict()
AttributeError: module 'weakref' has no attribute 'WeakValueDict'
```

### System Information

python version: 3.8.12
steam.py version: 0.8.7
aiohttp version: 3.8.1
betterproto version: 2.0.0b4
operating system info: Windows-10-10.0.19044-SP0

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username/password/secrets from display, if visible.

**Comment by Gobot1234** [comment]
Thanks for catching this, V0.8.8 should now have this fixed
