### ISSUE TITLE
Implement anonymous login

### ISSUE THREAD

**Issue by Polsaker** [Gobot1234/steam.py#121]
### Summary

Anonymous login for the steam client commands that support it

### What is the feature request for?

The core library

### The Problem

Some commands like fetch_product_info don't really require login. As it is currently in this library, those functions don't work if you don't login

### The Ideal Solution

Either make the methods work without login or add an `anonymous_login()` function like in the other steam libs

**Comment by Gobot1234** [comment]
I'm going to look into whether or not this is possible, my main concern is that I didn't think you could use the web-socket to login to an account but, this was something I planned on looking into to make the entire library faster to start up (for full release) and lazily fetch cookies like sessionid etc.

**Comment by Gobot1234** [comment]
Ok I've looked into this more and it seems to be possible, this will be supported in V1.
