### ISSUE TITLE
Bot reacts to his own messages, problematic with "-" as prefix and the help command

### ISSUE THREAD

**Issue by TECHNOFAB11** [Gobot1234/steam.py#18]
### Summary

The bot reacts to his own messages, when sending the help command for example it throws the CommandNotFound error because it cant find the command "-=" as it recognized the "-" as prefix

### Reproduction Steps

Add "-" as prefix

### Expected Results

It should ignore it

### Actual Results

`steam.ext.commands.errors.CommandNotFound: the command -= was not found`

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username/password from display, if visible.

### System Information

Not needed

**Comment by Gobot1234** [comment]
Thanks for the bug report, 
I was planning on making a better help command format in the future anyways, which along with ignoring messages from the bot will alleviate this issue.
