### ISSUE TITLE
Error with WS after running for long time

### ISSUE THREAD

**Issue by TECHNOFAB11** [Gobot1234/steam.py#19]
### Summary

My bot runs 24/7 and around 6 hours after having started it threw the AttributeError seen below

### Reproduction Steps

Default steam Bot class, with multiple prefixes, a owner_id and the shared_secret in the start() method to auto generate the 2FA codes. The issue probably is that the WS connection was closed, i guess.

### Expected Results

Catching the error if its inevitable and reconnecting

### Actual Results

```
...
  File "/usr/local/lib/python3.8/site-packages/steam/client.py", line 453, in start
    await self.connect()
  File "/usr/local/lib/python3.8/site-packages/steam/client.py", line 472, in connect
    await self._connect()
  File "/usr/local/lib/python3.8/site-packages/steam/client.py", line 464, in _connect
    await self.ws.poll_event()
AttributeError: 'NoneType' object has no attribute 'poll_event'

```

### Checklist

- [x] I have searched the open issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [x] I have removed my username/password from display, if visible.

### System Information

Python 3.8.4
Steam.py Version 0.3.0
Running inside of Docker, with `python:3.8` image

**Comment by Gobot1234** [comment]
I think this should be fixed now, but considering how persistent this issue has been I'd appreciate if you gave it another test after pulling from the repo.

**Comment by Gobot1234** [comment]
Appears to be fixed.
