### ISSUE TITLE
AssertionError at on_user_invite_accept

### ISSUE THREAD

**Issue by schrotle** [Gobot1234/steam.py#217]
Hello, 
I'm getting following error when using on_user_invite_accept(invite).
I guess this error is occurring because invite.invitee can be SteamID and more likely a User object.

Traceback (most recent call last):
  File "C:\bot-env\lib\site-packages\steam\utils.py", line 838, in maybe_coroutine
    return await value
  File "C:/bot-env\lib\site-packages\steam\state.py", line 1187, in process_friends
    assert not isinstance(invite.invitee, SteamID)
AssertionError

**Comment by Gobot1234** [comment]
What version of the code are you running?

**Comment by schrotle** [comment]
Version 0.9.7

**Comment by hanipk1998** [comment]
having the same problem

**Comment by Gobot1234** [comment]
Thank you for reporting this. This issue is resolved in the latest version of 0.9
