### ISSUE TITLE
example for sending a trade offer to friend or tradeurl

### ISSUE THREAD

**Issue by hanipk1998** [Gobot1234/steam.py#222]
### Summary

example of sending trade 

### What is the feature request for?

The core library

### The Problem

I can not figure out how to send a trade offer to a URL link and print trade sent

### The Ideal Solution

a simple example could give me the idea

### The Current Solution

looking for solutions.

**Comment by Gobot1234** [comment]
The issue tracker isn't for programming help, if you want help please join the discord server https://discord.gg/MQ68WUS
