### ISSUE TITLE
can't start Quick Example

### ISSUE THREAD

**Issue by InsDev** [Gobot1234/steam.py#23]
When start Quick Example have error:
from .enums import EInstanceFlag, EPersonaState, EPersonaStateFlag, EResult, EType, ETypeChar, EUniverse
ImportError: cannot import name 'ETypeChar' from 'steam.enums'

win10

**Comment by Gobot1234** [comment]
FYI if someone is viewing this in the future, this is likely due to having https://github.com/ValvePython/steam installed in the same environment as steamio. To fix this run something to the effect of:
```sh
python3 -m pip uninstall steam steamio
python3 -m pip install steamio
```
