### ISSUE TITLE
user.send(trade) breakes the code and doesn't continue to next line

### ISSUE THREAD

**Issue by hani9898** [Gobot1234/steam.py#231]
### Summary

sending trade might have problems

### Reproduction Steps

    trade = steam.TradeOffer(token=token, message=f"hello {order_id}", sending=item_to_send, receiving=None)

    await user1.send(trade=trade)
    print("Doesn't Print this !")
    
    
    i have integrated my steambot to discordbot, trade gets created and confirmed almost instantly but as i showed on the example above print("Doesn't Print this !") will not happen and the rest of the function wont happen...

### Expected Results

it should continue to next line of code and print the   print("Doesn't Print this !")

### Actual Results

code breakes on user.send(trade=trade)
trade is sent and confirmed but code breakes

### System Information

windows 11 - latest version of python and steam and discord library

### Checklist

- [X] I have searched the issues for duplicates.
- [x] I have shown the entire traceback, if possible.
- [X] I have removed my username/password/secrets from display, if visible.

**Comment by Gobot1234** [comment]
Should be fixed by https://github.com/Gobot1234/steam.py/commit/46102f10448ba74b9de871d384c6d63d203d7633
