### ISSUE TITLE
DeprecationWarning

### ISSUE THREAD

**Issue by jiajiaxd** [Gobot1234/steam.py#288]
### Summary

DeprecationWarning

### Reproduction Steps

Use this library on python 3.10 or above

### Expected Results

run the program with no such warning

### Actual Results

![图片](https://github.com/Gobot1234/steam.py/assets/51043917/c4a43878-c95e-4ff7-bfaa-a24d346203ca)

### System Information

python version: 3.10.9
steam.py version: 0.9.9
aiohttp version: 3.8.3
betterproto version: 2.0.0b4
operating system info: Windows-10-10.0.22621-SP0

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username, password, shared/identity secrets and refresh/access tokens from display, if visible.

**Comment by Gobot1234** [comment]
This wasn't fixable without having a large breaking change and hence has only been fixed in V1.

(This code won't error put until 3.14 or something so you can safely ignore the warning)

**Comment by jiajiaxd** [comment]
ok
What's more,your work is really great!especially the detailed description of each method and class.
