### ISSUE TITLE
Add 'active_only' parameter to the 'trade_history' method

### ISSUE THREAD

**Issue by jiajiaxd** [Gobot1234/steam.py#289]
### Summary

Add 'active_only' parameter to the 'trade_history' method

### What is the feature request for?

The core library

### The Problem

The lib cannot fetch active trade offer history only.

### The Ideal Solution

I would like to request the addition of an 'active_only' parameter to the 'trade_history' method. This parameter would enable us to retrieve only active trade offers. Currently, the method returns all trade history, including both active and inactive offers. By adding this parameter, it would provide greater flexibility and efficiency when working with trade data.

Thank you for considering this enhancement.

**Comment by Gobot1234** [comment]
This is something I did consider adding in the past, but I was under the impression that all active trade offers should be in [`Client.trades`](https://steam-py.github.io/docs/latest/api/#steam.Client.trades) but if that is no the case then I'll add support for this.

IIRC my main issue with this is that `TradeOffer`s yielded by `trade_history()` are actually `Trade`s (this is something I need to look into https://github.com/users/Gobot1234/projects/3/views/1?filterQuery=decide&pane=issue&itemId=25123033) I think, which is different from an offer in that they don't have an `tradeofferid` field (`.id`) (they have `tradeid` though (`._id`)) so they can't actually be accepted/confirmed, might be wrong on this though as I haven't taken that much time to investigate it.

**Comment by Gobot1234** [comment]
@jiajiaxd can you confirm whether or not all active trades are in `Client.trades` or do you still want this feature for some reason?

**Comment by jiajiaxd** [comment]
> @jiajiaxd can you confirm whether or not all active trades are in `Client.trades` or do you still want this feature for some reason?

Yes, I can confirm all the active tradrs.
It seems that this feature is not necessary for my project any more.
