### ISSUE TITLE
Add an option to ignore SSL verification for the steam.Client class

### ISSUE THREAD

**Issue by jiajiaxd** [Gobot1234/steam.py#306]
### Summary

Add an option to ignore SSL verification for the steam.Client class

### What is the feature request for?

The core library

### The Problem

In certain regions like China, accessing Steam can be challenging and often requires the use of a reverse proxy. This often leads to SSL verification failures. Having an option to ignore SSL verification would make the library more usable in these cases.

### The Ideal Solution

The ideal solution would be to add a parameter to the steam.Client class that allows users to ignore SSL verification. This would make it easier for users in regions where access to Steam is restricted or difficult.

### The Current Solution

This is a requests auth example, but do not work on aiohttp.
```
class accelerator:
    def __call__(self, r):
        domain_list = [
            "steamcommunity-a.akamaihd.net",
        ]
        domain = re.search(r"(https?://)([^/\s]+)", r.url).group(2)
        r.headers["Host"] = domain
        r.url = re.sub(r"(https?://)([^/\s]+)(.*)", r"\1" + random.choice(domain_list) + r"\3", r.url)
        return r
```

**Comment by Gobot1234** [comment]
I'm not sure if this is a feature aiohttp supports I'll have to take a look

**Comment by lupohan44** [comment]
The following code is what I used:

```
        if self._session is None:
            self._session = self._create_session()
        # If url is a string, convert it to URL object
        if isinstance(url, str):
            url = URL(url)

        # Get the host, port, and uri components from the URL object
        host = url.host
        host_hook = 'steamcommunity-a.akamaihd.net'
        if host == 'steamcommunity.com':
            host_hook = 'steamcommunity-a.akamaihd.net'
        elif host == 'store.steampowered.com':
            host_hook = 'steamstore-a.akamaihd.net'
        elif host == 'help.steampowered.com':
            host_hook = 'eaassets-a.akamaihd.net'
        uri = url.path.lstrip('/')
        kwargs.setdefault('headers', {})
        kwargs['headers']['Host'] = host
        response = await self._session.request(method, f'https://{host_hook}/{uri}', **kwargs)
```

However, in this code, the cookies related function will not work, so I have to implement a new cookies function like this:

```
    def cookies(self, domain: str = 'steamcommunity.com') -> Mapping[str, str]:
        host_hook = 'steamcommunity-a.akamaihd.net'
        if domain == 'steamcommunity.com':
            host_hook = 'steamcommunity-a.akamaihd.net'
        elif domain == 'store.steampowered.com':
            host_hook = 'steamstore-a.akamaihd.net'
        elif domain == 'help.steampowered.com':
            host_hook = 'eaassets-a.akamaihd.net'
        if self._session is None:
            raise RuntimeError('Session is not initialized')
        cookies = {}
        for cookie in self._session.cookie_jar:
            if cookie['domain'] == host_hook:
                cookies[cookie.key] = cookie.value
        return cookies
```

Hopefully, this code will help.

**Comment by nutterthanos** [comment]
usually with requests you can just put verify=False

**Comment by Gobot1234** [comment]
This library doesn't use requests, is there a way to do this with aiohttp?

**Comment by nutterthanos** [comment]
> This library doesn't use requests, is there a way to do this with aiohttp?

ssl=False

**Comment by Gobot1234** [comment]
I've implemented this via a kwarg that you can pass to Client. If you want to disable ssl do `Client(ssl=False)`. Thanks for your patience with this
