### ISSUE TITLE
Empty reactions in group channel messages

### ISSUE THREAD

**Issue by truenicoco** [Gobot1234/steam.py#329]
### Summary

Empty reactions in group channel messages

### Reproduction Steps

Fetch the reactions for a group message.

### Expected Results

The list of emojis should be in there.

### Actual Results

It's empty.

### System Information

Here's the output from my laptop, but it's probably irrelevant to the issue.

python version: 3.11.4
steam.py version: 1.0.0a2658+g1bcecabc
aiohttp version: 3.8.4
betterproto version: 2.0.0b5
operating system info: macOS-13.5.2-arm64-arm-64bit

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username, password, shared/identity secrets and refresh/access tokens from display, if visible.

**Comment by Gobot1234** [comment]
Steam now seem to require the limit field to be set for requests
