### ISSUE TITLE
AppInfo Init function throws error for app 1133290

### ISSUE THREAD

**Issue by AbdulDridi** [Gobot1234/steam.py#330]
### Summary

Client fetch_product_info is failing for certain apps (namely app 1133290)

### Reproduction Steps

Call fetch_product_info on the steam app 1133290

### Expected Results

Get the serialized AppInfo object related to that app

### Actual Results

Get this error - the depot object it expects is an empty string rather than a dictionary:

![Screenshot 2023-09-11 at 14 01 26](https://github.com/Gobot1234/steam.py/assets/15160037/875cd7ba-e9ca-4611-9c5c-d12c441d2d34)

here is a memory snapshot through the debugger (try statement was added manually by myself):
![Screenshot 2023-09-11 at 14 09 16](https://github.com/Gobot1234/steam.py/assets/15160037/2a72806b-452f-4deb-aff3-295068d109d2)

### System Information

python version: 3.11.1
steam.py version: 1.0.0a2809+g372f918
aiohttp version: 3.8.4
betterproto version: 2.0.0b6
operating system info: macOS-12.2-x86_64-i386-64bit

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username, password, shared/identity secrets and refresh/access tokens from display, if visible.

**Comment by Gobot1234** [comment]
Thanks for the bug report
