### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by NikittyS** [Gobot1234/steam.py#6]
Hello. First of first, you created an awesome bot. Very easy to start.

But I'm need some help. I tried your examples and got errors.

- Mac OS
- Python 3.8.2

**1. comment_monitor.py**
![comment](https://user-images.githubusercontent.com/60339254/80294974-d6260b00-87b1-11ea-95be-0fc15340faec.png)

And doesn't delete a comments with URL (not from friend).

**2. trade.py**
Everything is good, but when i got a trade (as gift), script doesn't accept trade automatically.

![trade](https://user-images.githubusercontent.com/60339254/80295088-0ae69200-87b3-11ea-80f6-20ceccc25cab.png)

Maybe I'm doing something wrong.

**3. Send trade**
Just a question. Can you write example how get my (cs:go) inventory list and send trade (with some item) to user?

Thank you.

**Comment by Gobot1234** [comment]
Thanks for the bug report.

1. Both issues should be fixed.
3. There is an example in the FAQ which you can [read here](https://steampy.rtfd.io/en/latest/faq.html#how-do-i-send-a-trade)

I'm currently working on 2.

**Comment by Gobot1234** [comment]
2. Should now be fixed, I'll push the changes I've made now.
