### ISSUE TITLE
on_trade_accept

### ISSUE THREAD

**Issue by TrixiS** [Gobot1234/steam.py#88]
### Summary

on_trade_accept is not called when partner accepts the trade. So its called only when client accepts the trade and when it accepts some trade, it fires this event for the trade that was accepted by the partner and then for the trade accepted by the client

### Reproduction Steps

1. Send trade on client side
2. Accept it on partner side
3. No on_trade_accept event after partner accept the trade
4. Send a trade to client from partner side
5. Accept the trade on client side
6. See the message about client accepted the trade and the message about partner accepted the previous trade

### Expected Results

on_trade_accept should be fired when partnter accepts the trade sent by client

### Actual Results

No on_trade_accept is fired after partner trade accept

### System Information

Started a steam client using bot.run like in examples

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username/password/secrets from display, if visible.

**Comment by TrixiS** [comment]
I need to mention that:

1. The partner of the trades is not a friend
2. I construct a TradeOffer object from token and item asset
3. This thing is being rised then I'am trying to send a trade (actually the trade is already sent when this exception appears)
![image](https://user-images.githubusercontent.com/55791844/147363424-8062e8db-11d1-4293-a31b-bc1639c04a02.png)

**Comment by Gobot1234** [comment]
Can you update to the latest version? I know I have fixed the ValueError. The other thing I'm not too sure about

**Comment by TrixiS** [comment]
> 

I've just updated the library (from github). ValueError is fixed, but the first problem is still happening

**Comment by Gobot1234** [comment]
I can't reproduce this on main anymore. Can you confirm this has been fixed?

**Comment by TrixiS** [comment]
No, I can't. The same thing happens, when a partner accepts the trade, no on_trade_accept is being dispatched. But when the client itself accepts the trade, the previous event fires.

So, it seems for me that on_trade_accept fires after on_trade_receive handler (I have trade.accept() in it for gift trades)

**Comment by TrixiS** [comment]
And I have these messages in the log
![image](https://user-images.githubusercontent.com/55791844/147380757-110e2e81-57d7-486b-a820-70b5b1582fba.png)

**Comment by TrixiS** [comment]
Thank you a lot. The problem is fixed

**Comment by ibn-icena** [comment]
> > 
> 
> I've just updated the library (from github). ValueError is fixed, but the first problem is still happening

@TrixiS I am also facing the same problem about on_trade_accept event not being triggered like you. Could you please tell, how you fixed your issue?

**Comment by TrixiS** [comment]
> > > 
> > 
> > 
> > I've just updated the library (from github). ValueError is fixed, but the first problem is still happening
> 
> @TrixiS I am also facing the same problem about on_trade_accept event not being triggered like you. Could you please tell, how you fixed your issue?

I just updated the library from ghub

pip install git+https://github.com/Gobot1234/steam.py

**Comment by TrixiS** [comment]
The first problem with on_trade_accept still happens

**Comment by Gobot1234** [comment]
Does this only not dispatch if they aren't friends?

**Comment by TrixiS** [comment]
> Does this only not dispatch if they aren't friends?

If I tested it correcly, it does not. I think I just had to mention this

**Comment by Gobot1234** [comment]
This is in 0.8.5 now. Thank you for reporting this!
