### ISSUE TITLE
500 Server Internal Error on trade send

### ISSUE THREAD

**Issue by TrixiS** [Gobot1234/steam.py#89]
### Summary

Sending a trade offer to a user results in an error

### Reproduction Steps

I have just updated the library to the version of 0.8.5. And now I can't send trades =)

1. Fetch a user from steam id64 e. g. ```await client.fetch_user(id)```
2. Create a steam.TradeOffer object from token and an item (I used only one item that was taken from inventory directly)
```trade_offer = steam.TradeOffer(token=trade_token, items_to_send=[item])```
3. ```await user.send(trade=trade_offer)```
4. user.send method raises exception
5. I've tried to send a trade to a non-friend (errors) and then add a partner to the friend list (didn't help me)

### Expected Results

Successfully sent trade offer as it was in the previous versions of the library

### Actual Results

Exception

### System Information

Python 3.8
Library version 0.8.5 (from github)

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username/password/secrets from display, if visible.

**Comment by TrixiS** [comment]
![image](https://user-images.githubusercontent.com/55791844/147510437-ab76a24f-a6ac-42e7-a0a2-658c6fd97ddb.png)

**Comment by Gobot1234** [comment]
Considering I didn't change any of that code I think you should check out https://steamerrors.com/15
https://github.com/Gobot1234/steam.py/compare/V.0.8.4...V.0.8.5

**Comment by TrixiS** [comment]
> Considering I didn't change any of that code I think you should check out https://steamerrors.com/15 [V.0.8.4...V.0.8.5](https://github.com/Gobot1234/steam.py/compare/V.0.8.4...V.0.8.5)

But lol, I can send trade through the offical steam client

**Comment by Gobot1234** [comment]
![image](https://user-images.githubusercontent.com/50501825/147511262-0bab0fb9-04a1-4ca2-98b7-ecd47fb2e6f4.png)
![image](https://user-images.githubusercontent.com/50501825/147511306-32cbfe2d-2dcb-4de8-810f-74f4887eb769.png)
I'll check with someone who isn't a friend but I can't reproduce this.

**Comment by TrixiS** [comment]
Ok, it was my bad. Thank you for all of your work and such fast answers! The library is awesome =)

**Comment by Gobot1234** [comment]
No problem.
