### ISSUE TITLE
Looking to decrypt encrypted application tickets

### ISSUE THREAD

**Issue by ryan1336** [Gobot1234/steam.py#9]
Hi,

I'm looking for help decrypting encrypted application tickets.

Using ValvePython's Steam library (pip install steam)

`    data = "CAEQ8IrOxw0YBCA+KnAsX1ZReXWSFz1IHPQ6sBSTBK3hj2co79vrystWUrqUyOz9ueLpMy59R0WAirzid93gVGyT7wb3Ptwmdtqhb+UtqIupxHQ7n5k6HCCAh4Us3jC3a64hhJ9XjEEzorxzciVbSgQmMASYBGCtBjRV7f1R"
    data = base64.b64decode(data)
    keyx = key.encode()
    decrypted_data = crypto.symmetric_decrypt(crypto.pad(data), keyx)

    import struct
    s = struct.unpack_from("IIQIIIINNhIhhhxx", decrypted_data[:64])`

I wonder if your library can accomplish it instead as I've hit a wall using Py Steam, probably have the struct all wrong. How can I contact you by the way? Do you do consultations?

**Comment by Gobot1234** [comment]
I have no clue sorry, if you want to get in contact with Rosen, the creator of ValvePython/steam he may be more helpful. https://webchat.freenode.net/#steamkit

**Comment by ryan1336** [comment]
Yeah, I've got this far as well the problem is the decrypted data, I can't
get the struct quite right:

    decrypted_data = crypto.symmetric_decrypt(test.encrypted_ticket, keyx)
    if not zlib.crc32(decrypted_data) == test.crc_encryptedticket:
        return False
    decrypted_ticket_len = len(test.encrypted_ticket)
    s = struct.unpack_from("IIllIIINNhIhhh", decrypted_data)
    print(s)

**Comment by Gobot1234** [comment]
Structs confuse me so no clue on that front.
