### ISSUE TITLE
Occassionally getting 401s when interacting with the API

### ISSUE THREAD

**Issue by TrixiS** [Gobot1234/steam.py#93]
### Summary

user.send(trade=trade) result in an error

### Reproduction Steps

1. Fetch a user from steam id 64
2. Fetch bot inventory
3. Get item from class_id 
4. Construct a trade from this item and trade token
5. Send a trade to the user
6. Decline the trade on the client side
7. Repeat 2, 3, 4, 5 steps
8. Got an error 401 Unauthorized
![image](https://user-images.githubusercontent.com/55791844/148822211-d64c95de-01ed-4c61-a0f8-0c9484f9bfbc.png)

### Expected Results

Successfully sent trade offet

### Actual Results

Error 401

### System Information

python 3.8
Ubuntu 20
Version of the library 0.8.5 

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username/password/secrets from display, if visible.

**Comment by Gobot1234** [comment]
Do you have a code snippet for this?

**Comment by TrixiS** [comment]
![image](https://user-images.githubusercontent.com/55791844/148822995-c5fa0885-95d3-48bd-8468-5fcceea8ef20.png)
![image](https://user-images.githubusercontent.com/55791844/148823016-3c66b708-d523-4423-b69b-dc6429c3f4b5.png)
![image](https://user-images.githubusercontent.com/55791844/148823050-5845a1a0-00d8-42ec-bdef-4eaee06e56b2.png)

**Comment by TrixiS** [comment]
And another thing. Error still happens on every trade I'am sending after that errored trade, but if I restart the bot, error disappears

**Comment by TrixiS** [comment]
Could this be fixed?

**Comment by Gobot1234** [comment]
I'm sorry I haven't had time to properly debug this, I'll try and take a look at this over the weekend

**Comment by TrixiS** [comment]
> I'm sorry I haven't had time to properly debug this, I'll try and take a look at this over the weekend

Your fast answers are awesome. Thank you :)

**Comment by Gobot1234** [comment]
I can't reproduce this at least not with the steps provided. You might have been temporarily banned by Steam.

**Comment by TrixiS** [comment]
I can send offers from official client at the same time

**Comment by Gobot1234** [comment]
IDK what's up then if it works the first time but then not after declining a trade.

**Comment by Gobot1234** [comment]
@TrixiS I'm curious if you can reproduce this on a different account on a different network or after not using the account you are currently using for a week or so.

**Comment by Gobot1234** [comment]
@TrixiS can you also comment on whether or not you were using the web browser to send trades or the actual Steam app?

**Comment by Gobot1234** [comment]
Coming back to this it's possible that the account was logged out by Steam.

**Comment by Gobot1234** [comment]
Closing as this is stale
