### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by somespecialone** [Gobot1234/steam.py#96]
### Summary

New release with fixing some bugs

### What is the feature request for?

The core library

### The Problem

`gateway.send_gc_message` and `client._handle_ready` raises AttributeError when call `client.user.inventrory(CSGO)`

### The Ideal Solution

Actually, problem in typos and fxed already, but fix not in release. So creating new release will be good option

**Comment by Gobot1234** [comment]
steam-ext-csgo already should have this fixed if you are using the latest version as it depends on the main branch and doesn't use full releases.

**Comment by somespecialone** [comment]
My project use your library, and depends on explicit version. I rewrote dependency to main branch and hope there is no be breaking changes

**Comment by Gobot1234** [comment]
I generally guarantee that there aren't breaking changes to public API in between major releases but you seem to be relying on a lot of internals (some of which you shouldn't have to) but they are subject to breakages in any version bump.

**Comment by somespecialone** [comment]
Unfortunally, i issued dependency error in poetry due to few packages relyes on git main revision, so asking you to create new release.

**Comment by Gobot1234** [comment]
Alright I'll try and do this at some point tomorrow

**Comment by Gobot1234** [comment]
I'll close this when it's done
